### ISSUE TITLE
text display mirroring HORIZONTAL_ZIGZAG_MATRIX

### ISSUE THREAD

**Issue by quarterturn** [AaronLiddiment/LEDText#1]
I'm confused as to how to get my HORIZONTAL_ZIGZAG_MATRIX APA102 strips to display properly. I have data entering on the upper left and then zig-zagging back to the lower left over 8 strips of 44 LEDS. My text display ends up flipped both ways.

Looking at your examples, there is a constructor cLEDMatrix<MATRIX_WIDTH, MATRIX_HEIGHT, MATRIX_TYPE> leds;
I can use 'leds.' to access the various mirror functions, but they have no effect on the final output.

**Comment by AaronLiddiment** [comment]
You can use a negative 8 for the height parameter to flip the origin for the matrix functions to the lower edge. so...
cLEDMatrix<44, -8, HORIZONTAL_ZIGZAG_MATRIX> leds;
This will make 0,0 of your matrix the bottom left corner.
The mirror functions would work but you would have to call them after each call to cLEDText update.

**Comment by quarterturn** [comment]
> On May 28, 2016, at 12:04 PM, Aaron Liddiment <notifications@github.com> wrote:
> 
> You can use a negative 8 for the height parameter to flip the origin for the matrix functions to the lower edge. so...
> cLEDMatrix<44, -8, HORIZONTAL_ZIGZAG_MATRIX> leds;
> This will make 0,0 of your matrix the bottom left corner.
> The mirror functions would work but you would have to call them after each call to cLEDText update.
> 
> 
> 
Ah, spoke too soon! -8 corrects the text but breaks the background color stuff - it disappears.

|\ |  (¯  \/ |¯\  |V| |\ ¯|¯ |¯) | \/ | | | |¯\ (¯   /¯  /\ |V|
|-||_ (_  /\ |_/ @| | |-| |  | \ | /\ |^| | |_/ (_ . \_  \/ | |
