### ISSUE TITLE
Last line in matrix not updated correctly after text passed

### ISSUE THREAD

**Issue by bombcheck** [AaronLiddiment/LEDText#10]
Just noticed a strange behaviour on my 8x8 matrix: After the text scrolled out of view, the last line stays black for some time before it gets updated again from the running background effect:

![](https://breakout.bernis-hideout.de/git/20180404_123758_1_small.gif)

Any idea?

**Comment by bombcheck** [comment]
Strange: If I define MATRIX_WIDTH with 9 instead of 8 (8 would be to correct physical width) the effect described is gone...

**Comment by AaronLiddiment** [comment]
Are you checking for a return of -1 from the Update function?
And if you do check for the -1 do you then stop calling the Update function until you have done another SetText?
I've not noticed that this problem before but most of my tests involved overlaying the background or using the dim background options.

**Comment by bombcheck** [comment]
Yes i check for the return code. I just scroll the text one time. So after the Update Function gives me a -1, a stop calling it before it is time to scroll the text again.

But I think I got it fixed: I defined the Char-Array for my text to long: 12 instead of the needed 6. Now the matrix behaves normal when the text scrolled out.
