### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by TheGreyDiamond** [AaronLiddiment/LEDText#11]
Hi,
I'm trying to compile the first example. But I'm getting the following error: `LED-text:3:23: error: LEDMatrix.h: No such file or directory`. What am I doing wrong?

**Comment by AaronLiddiment** [comment]
You also need the LEDMatrix library

**Comment by TheGreyDiamond** [comment]
And from where can I get it?

**Comment by AaronLiddiment** [comment]
It’s another of my repositories, just click on my name and you should see it.

**Comment by TheGreyDiamond** [comment]
Does not work, but now I have another problem... Here is the compiling log: [Pastebin](https://pastebin.com/EKmmfchn)

**Comment by TheGreyDiamond** [comment]
Fixed it!
