### ISSUE TITLE
Mirrored Text

### ISSUE THREAD

**Issue by keukenrol** [AaronLiddiment/LEDText#16]
Hi

congratulations on the wonderful library, I have been searching for a library offering this many functions for a long time.
Unfortunately I have some issues with the way the hardware is set-up. The classic matrix is going from left to right. Well mine is inverted, the LED on the right bottom is the first and the LED on the left top of the matrix is the last. Thus, all my text is mirrored. 
For example, the TextExample1 function with a VERTICAL_ZIGZAG_MATRIX type. **When the text LEFT SCROLL comes up, it is mirrored and goes right.**

Using the NeoMatrix library I could use this:

> Adafruit_NeoMatrix(96, 8, DATA_PIN,
>                             NEO_MATRIX_BOTTOM    + **NEO_MATRIX_RIGHT** +
>                             NEO_MATRIX_COLUMNS + NEO_MATRIX_PROGRESSIVE + NEO_MATRIX_ZIGZAG,
>                             NEO_GRB            + NEO_KHZ800);
The NEO_MATRIX_RIGHT parameter is what I am looking for. It defines the LED order (from back to front, counter intuitive).
How can I solve this?

Thanks!

EDIT: Found out about the other issue described here and fixed: https://github.com/AaronLiddiment/LEDText/issues/1

**Comment by AaronLiddiment** [comment]
I did try to respond but Github wouldn't let me log in for a while. Glad you found the answer.
