### ISSUE TITLE
text is mirrored

### ISSUE THREAD

**Issue by MADxHAWK** [AaronLiddiment/LEDText#21]
First of all, happy new year ;) 

Well im playing around with your library but ran into some issues. All texts are diplayed in mirror writing. 

Im Using 8x32 Neopixel Matrix. The Layout of tie Matrix Tile is Columns and the first pixel is in the bottom right corner, 
The tiles are aranges int a 2 colums 3 rows matrix same as the tile itself.
```
4 --- 3
|       |
5     2
|       |
6     1
```

Im running the Code using your LEDMatrix library on an Heltec ESP32 Wifi Kit and can draw lines from 0, 0 to 63, 23
My Matrix initialisation is:

```
#define MATRIX_TILE_WIDTH       32           // Width of each panel 
#define MATRIX_TILE_HEIGHT      8            // Height of each panel
#define MATRIX_TILE_H           3            // number of matrices arranged horizontally
#define MATRIX_TILE_V           2            // number of matrices arranged vertically
#define MATRIX_WIDTH            (MATRIX_TILE_WIDTH * MATRIX_TILE_H)
#define MATRIX_HEIGHT           (MATRIX_TILE_HEIGHT * MATRIX_TILE_V)
#define MATRIX_SIZE             (MATRIX_WIDTH * MATRIX_HEIGHT)
#define MATRIX_PANEL            (MATRIX_WIDTH * MATRIX_HEIGHT)
#define NUM_LEDS                (MATRIX_WIDTH * MATRIX_HEIGHT)

cLEDMatrix<MATRIX_TILE_WIDTH,MATRIX_TILE_HEIGHT, VERTICAL_ZIGZAG_MATRIX, MATRIX_TILE_H, MATRIX_TILE_V,VERTICAL_ZIGZAG_BLOCKS> leds;

```
So i have no clue why text is displayes mirrored even it moves in the right direction 
Im Using your Example Code "TextExample 1"
Any hints would be aprecciated, thank you

**Comment by keukenrol** [comment]
The width or height can be negative values as well, try that out. For example width -32.

**Comment by elisaado** [comment]
Thank you @keukenrol. 32, -8 as the width and height accordingly worked for me.
