### ISSUE TITLE
Documentation for EFFECT_HSV_xx

### ISSUE THREAD

**Issue by CobaltEcho** [AaronLiddiment/LEDText#25]
Is there documentation anywhere on what the following effects do?  I read the wiki and the Function List page tells how to use them, but not what the effect actually is.

```
EFFECT_HSV_CV
EFFECT_HSV_CH
EFFECT_HSV_AV
EFFECT_HSV_AH
```
And the gradient versions:
```
COLR_GRAD_CV
COLR_GRAD_AV
COLR_GRAD_CH
COLR_GRAD_AH
```

**Comment by AaronLiddiment** [comment]
The Effect ones are listed on Page 4 of the Wiki and the Grad ones are for use with the function call SetTextColrOptions.
Basically the V refers to vertical change, and the H refers to horizontal change.
The C then refers to the character (graduates over the character width or height), and the A refers to the text area (graduates over the text area width or height).
I hope that makes sense.
The Effect ones are for use as part of the unsigned char text array that you pass to SetText whereas all the defines upto the Effect ones in the header are to be used with the SetTextColrOptions(), SetBackgroundMode() and SetOptionsChangeMode() calls.

**Comment by CobaltEcho** [comment]
Thanks again for your help!  My project is coming along really well with your resources!
