### ISSUE TITLE
Is this library slow? Seems like it from my testing.

### ISSUE THREAD

**Issue by jeremyjacob** [AaronLiddiment/LEDText#32]
I am using the ESP8266 so maybe the ESP32 would be more adequate but I was getting serious framerate drops using the text over top a noise pattern. This library seems to only work well when no other patterns are shown. 

If anyone can suggest an alternative I would greatly appreciate it!

**Comment by jeremyjacob** [comment]
It's also entirely possible I am using it wrong. I am basically using the first example and then using FastLED's blend() to merge it with another CRGB[] driven by inoise8().

**Comment by AaronLiddiment** [comment]
Why did you not use the BackgroundMode function? It allows you to leave the background untouched so only the letter pixels are rendered to the LEDs. Take a look at the Function List in the Wiki.
I am not familiar with the inoise8() you refer to but I presume it takes a CRGB array pointer and a size so in my exmaple1 the pointer of the Matrix is `leds[0]` and the number of leds is `leds.Size()`.
Do the `inoise8()` call before calling the `UpdateText` and in your setup use the `SetBackgroundMode(BACKGND_LEAVE)`
I think the Blend function would probably be slowing you down as it does some complex colour blending.
