### ISSUE TITLE
Mirrored Text

### ISSUE THREAD

**Issue by uaguilera1** [AaronLiddiment/LEDText#39]
Has anyone run into an issue where the text is mirrored?

**Comment by AaronLiddiment** [comment]
You need to read the cLEDMatrix wiki.
You can use a '-' sign before the width and/or height parameter for the cLEDMatrix declaration.
e.g.
#define MATRIX_WIDTH   68
#define MATRIX_HEIGHT  7
#define MATRIX_TYPE    HORIZONTAL_ZIGZAG_MATRIX
cLEDMatrix<-MATRIX_WIDTH, MATRIX_HEIGHT, MATRIX_TYPE> leds;

This would move the x origin to the opposite side of the matrix.

**Comment by uaguilera1** [comment]
Sorry, I tried to find where I could change that in the Wiki but should have taken a better look, Thank you, that solved it for me!
