### ISSUE TITLE
Dynamic score display

### ISSUE THREAD

**Issue by benlooi** [AaronLiddiment/LEDText#6]
Hello again,
I am trying to display a score in numbers with one decimal point on my matrix. 
In the example, the scrolling text uses const unsigned char array. I am wondering if the SetText function require unsigned char and how do I convert a string to unsigned char in Arduino. Here is my sample code:

cLEDMatrix<WIDTH, HEIGHT, MATRIX_TYPE> leds;

cLEDText Score;

float the_score;
unsigned char SCORE[]= {};
void setup () {
the_score=0;
Score.SetFont(MatriseFontData);
Score.Init(&leds, leds.Width(), Score.FontHeight() + 1, 0, 0);
Score.setText((unsigned char *)SCORE, sizeof(SCORE)-1);

}

void loop () {
//increase the score every cycle
the_score+=0.25;
//assign the_score to SCORE array ---this is where I am unsure
SCORE[0] = String(the_score,1);
if (Score.UpdateText() == -1)
//so the displayed text Score will keep changing every refresh cycle
    Score.SetText((unsigned char *)SCORE, sizeof(SCORE) - 1);
  else
    FastLED.show();
  delay(10);
}

**Comment by AaronLiddiment** [comment]
You do not allocate any memory for the score character array which will lead to memory corruption!

Replace:
unsigned char SCORE[]= {};
With:
String SCORE = "";

And change your SetText's to this:
Score.SetText(SCORE, SCORE.length());

And Finally change:
SCORE[0] = String(the_score, 1);
To:
SCORE = String(the_score, 1);

**Comment by benlooi** [comment]
Thanks for the tip! Great work, by the way on this. I hope to understand it more to contribute to this project. 
I am making a 39 x 18 matrix with ws2811 string leds. Using a China-power supply with 5v/40A that comes with 3 DC outs. I managed to power all by allocating each DC output to about 250 leds. May need to put in one more power supply to power the Arduino Mega and another set of ws2812bs strips.

**Comment by benlooi** [comment]
Hi. I am getting an error  when I do Score.SetText(SCORE,SCORE.length());    :
no matching function for call to 'cLEDText::SetText(String&, unsigned int)'

Any idea why?

**Comment by benlooi** [comment]
Alright, did some more digging into SetText. It requires unsigned char, so String as a parameter wouldn't work.
So the solution is to cast the String to unsigned char. Here's what I did that seems to work.
//get the string
SCORE= String(the_score,1);
//make a new variable that is an unsigned char
unsigned char displayScore[10];
//push SCORE string to the char array
SCORE.toCharArray(displayScore,10);
//finally for SetText...dunno what -1 does, just following the example
Score.SetText(displayScore, sizeof(displayScore) -1);

This got rid of the error.

**Comment by AaronLiddiment** [comment]
Well done :)
To be honest I have never used 'String', I would normally use sprintf to format data into unsigned char arrays. But I thought it would be easier as you had already started using it. I did mod one of the examples with String and it compiled with no errors for me but this could be down to which Arduino version you have installed.
But you do learn more when you have to work to find a solution ;)
BTW here is a sprintf example:
unsigned char displayScore[10];
float Score = 2.75;
sprintf(displayScore, "%9.1f", Score);  //  "      2.8"
or
sprintf(displayScore, "%09.1f", Score);  //  "0000002.8"

A char array is usually terminated with a 0x00 so the actual length of the data is usually it's size minus 1.

**Comment by Miniontoby** [comment]
Hey!

I am also trying to show dynamic text.

I got this code:
```cpp
String buffer = "HELLO WORLD"; // This is filled by Serial read..., but this is the value that I send to it

// ...

String TxtRaw = "\xdc            " + buffer; // \xdc = EFFECT_SCROLL_LEFT
const size_t size = TxtRaw.length() + 1;
unsigned char TxtSend[size];
//TxtRaw.getBytes(TxtSend, size); // Also tried this with no luck...
TxtRaw.toCharArray((char *)TxtSend, size);
ScrollingMsg.SetText((unsigned char *)TxtSend, sizeof(TxtSend) - 1);
```

But it doesn't work, cause it messes up the whole display...
And the second time I run it, then it displays an `=` for some reason...


Please help me out!

**Comment by AaronLiddiment** [comment]
I have just compiled up your code sample and dumped the TxtSend char array as bytes to the console with no issues.
`DC,20,20,20,20,20,20,20,20,20,20,20,20,48,45,4C,4C,4F,20,57,4F,52,4C,44,0`
So I am left wondering if you have declared the "unsigned char TxtSend[size]" and "SetText" within a function, then come back out of this function where you call the display function.
If so then you need to be aware of the difference between local and global variables. "Local" are allocated on the stack and only valid while in that function whereas "global" are allocated on the heap and will be valid in all your functions.

**Comment by Miniontoby** [comment]
Well yeah they both are defined in the `loop` function

The problem is that the `size` of TxtSend can variate... so that's why it is local... 

I can make it global with length 256... but now it seems to do random flashing when the text is gone.
And also when I enter a shorter text, the old text will still show...

Edit: I can of course give the SetText the length of the TxtRaw string instead...
That seems to work, but the 256 size is a bit too big for some other buffers...
So I guess I will reduce it... 77 is what seems to be the max now... well should be enough...

**Comment by AaronLiddiment** [comment]
It is a good idea to make sure you limit the buffer copy so you don't overwrite other memory, something like the following will make sure the copying of data never exceeds the TxtSend char array and will automatically adjust according to the size of the char array you declare.
`size_t Len = min(sizeof(TxtSend)-1, TxtRaw.length());`
`TxtRaw.toCharArray((char *)TxtSend, Len);`
`TxtSend[Len] = '\0';`
`ScrollingMsg.SetText((unsigned char *)TxtSend, Len);`
